### PR TITLE
User interface

### PR DESCRIPTION
**Pull request by BrianSammit**
Made user interface.

### CODE REVIEW

**Comment by kubilaycaglayan** [comment]
Hello Team :wave: 
Status: Invalid Code Review Request :no_entry_sign: 

Thanks for your effort :blush: 

Friendly reminder: You should make sure that your repo looks professional before review.
Please take a step back and read a lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.
Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there).
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

:bulb: Pull request message should be meaningful and explain what you have done and commits should be descriptive. Please read the instructions one more time to get a good understanding of them :blush: 

With all my respect... :pray:

**Comment by BrianSammit** [comment]
We made in this milestone a class board that makes the board where the users play the game and we made a class game that put the x or o in the position that the player wants to put, finally, we put messages on how the player has to play every single round.

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Finch Tabilo Sepulveda & Brian Cruz Rodriguez** 
Great job with the improvements to your project :muscle:  :muscle:
We still need to solve some issues:

- [x] make sure rubocop doesn't mark any offense in your code
- [x] game should display the board after the player move 
- [x] game should inform player if the selected move is a winning move
- [x] game should inform player if the selected move is a draw move
- [x] If game is not over, game should repeat all actions for the next player's move
- [x] The question about whether player wants to play or not might be ok to ask players if they want to play again, but it should be not included for the initial game. 
- [x] Some of your variables don't have descriptive names (inp1, inp2, arr, array), use descriptive names for your variables.

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:
Note: you don't need logic for this milestone, an interface is okay.
#### You can merge !!!

**Review by kobiyoyo — APPROVED** [review]
approved

**Pull request merged**
